feat: Update prompt language settings for summarization
zurawiki/gptcommit pull request #56
Opened 2023-02-16 10:44 UTC by zcf0508

https://github.com/zurawiki/gptcommit/issues/42

Hi, thanks for building this tool!

I'm a Chinese, so I need a configuration to set the language to use when generating the summary, like Chinese.

This is my work. And I am a novice in programming with rust, so if there are any mistakes, welcome to make suggestions.

2023-02-18 00:05 UTC, zurawiki requested changes
Thanks for the PR. Left some comments.

My main question is what happens when we select an unsupported language? Can we provide a clear list of supported languages?

2023-02-18 00:05 UTC, zurawiki commented on README.md
> +gptcommit config set prompt.lang english
We should use the standard locale language codes for selecting language. This will allow us to standardize usage across languages

2023-02-18 00:05 UTC, zurawiki commented on src/prompt.rs
> +pub fn format_prompt(prompt: &str, lang: &str, map: HashMap<&str, &str>) -> Result<String, Error> {
Don't add a function argument here, define a `language` property in the `map` variable and use the tera templating logic for this

2023-02-18 00:05 UTC, zurawiki commented on src/prompt.rs
> +    let new_prompt = format!("REMEMBER, ANSWER IN {}.\n{}", lang.to_uppercase(), prompt);
Add this to the prompts instead. This will be easier to extend in the longer term

2023-02-18 00:05 UTC, zurawiki commented on src/settings.rs
> +                    lang: Some("ENGLISH".to_string()),
Use the standard two-letter codes here

See: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

2023-02-18 00:05 UTC, zurawiki commented on src/summarize.rs
> +
Remove new line

2023-02-18 00:05 UTC, zurawiki commented on src/summarize.rs
>              HashMap::from([("file_diff", file_diff)]),
prompt lang should be in the HashMap here, not as a separate argument

2023-02-18 17:26 UTC, zurawiki requested changes
Thanks for the patch. Just some remaining comments and I think we are almost there

2023-02-18 17:26 UTC, zurawiki commented on src/summarize.rs
> +            HashMap::from([("file_diff", file_diff), ("ansewe_langurage", &self.prompt_lang)]),
This is great, just make sure to rename the output variable

2023-02-18 17:26 UTC, zurawiki commented on src/settings.rs
> +
I appreciate you supporting all of these languages from the beginning but avoid creating hashmaps when not required. We can list out the languages with an enum.



 ```suggestion
use std::string::ToString;
use strum_macros::Display;

#[derive(Display, Debug)]
#[strum(serialize_all = "kebab-case")]
enum Language {
    #[strum(to_string = "English")]
    En,
    #[strum(to_string = "Simplified Chinese")]
    ZhCn,
    #[strum(to_string = "Traditional Chinese")]
    ZhTw,
    #[strum(to_string = "Japanese")]
    Ja,
}

Then you can go from 

```rust
// "en" => Language::En
println!("{:?}", Language:from_str("zh-cn"));
// Language::En => "English"
println!("{}", Language::En.to_string());
```

Examples from the strum library:
https://github.com/Peternator7/strum/blob/master/strum_tests/tests/serialize_all.rs
https://github.com/Peternator7/strum/blob/master/strum_tests/tests/to_string.rs

2023-02-19 07:01 UTC, zcf0508 commented on README.md
> +gptcommit config set prompt.lang zh-cn
That sounds better. So which do you think is better, that I define a new `OutputSetting` or just change `prompt.lang` to `prompt.output_language`?

2023-02-19 12:35 UTC, zurawiki commented on README.md
> +gptcommit config set prompt.lang zh-cn
I think an OutputSetting makes the most sense. What do you think?

2023-02-20 10:20 UTC, zurawiki commented
For 1. This link might help

https://stackoverflow.com/questions/69292362/enum-to-str-str-to-enum

Look at the parse function

For two, you bring up a good point. We might need to add another prompt at the end to translate the whole commit message for non English languages. What do you think?

2023-02-21 02:09 UTC, zurawiki commented
Try making your changes in this function. Note you'll need to rebase as I did some refactoring.

https://github.com/zurawiki/gptcommit/blob/57747d10e81f54b110eda87944a1a2fe349213d2/src/summarize.rs#L55-L58

I would add the language prompt to the title and summary prompts and then add a new prompt to translate the file-level bullet points

2023-02-21 04:03 UTC, zcf0508 commented
Sorry, I have no idea about using `try_join`. I create a new function `commit_tanslate` to translate the result message.

2023-02-21 23:55 UTC, zurawiki approved these changes

2023-02-21 23:55 UTC, zurawiki commented on src/summarize.rs
> +        message = self.commit_tanslate(&message).await?;
```suggestion
        let message = lines.join("\n");

        let message = self.commit_tanslate(&message).await?;
```

You don't need the `mut` :)

2023-02-21 23:57 UTC, zurawiki commented
This looks great! As for the `try_join!` we could be smarter about how many round trips we need from OpenAi but we should be good for now

Note that the `lint` job is failing in CI

Run `just fix` and make sure all errors are resolved

2023-02-22 01:56 UTC, zcf0508 commented
Thanks for the review. I fixed the lint error and some typos.

2023-02-22 02:00 UTC, zcf0508 commented
Perhaps we have a new problem. 

If the user has an old configuration file, do they need to delete the old one and set it up again?

2023-02-22 03:51 UTC, zurawiki commented
The configuration files should be forward-compatible as long as we add fields and don't change default values. Do you have instructions to repro this issue?

2023-02-22 03:57 UTC, zcf0508 commented
I have only added the translation prompt and `output.lang` settings. I should have been overthinking it.

2023-02-22 14:58 UTC, merged